In [2]:
import numpy as np

arr = np.array([
    [
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]
    ],

    [
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]
    ],

    [
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]
    ]
])

print(arr.shape)

(3, 4, 5)


In [7]:
# Assignment: 3D Array Indexing & Slicing

# Section A – Access Individual Elements

# Write a statement to extract:

#10
print("Element at Array 0 Row 0, Column 0:", arr[0, 0, 0]) 
#24
print("Element at Array 0  Row 2, Column 4:", arr[0, 2, 4]) 
#37
print("Element at Array 1 Row 0, Column 3:", arr[1, 1, 2]) 
#43
print("Element at Array 1 Row 2, Column 3:", arr[1, 2, 3]) 
#54
print("Element at Array 2 Row 0, Column 4:", arr[2, 0, 4]) 
#66
print("Element at Array 2 Row 3, Column 1:", arr[2, 3, 1]) 
#58
print("Element at Array 2 Row 1, Column 3:", arr[2, 1, 3]) 
#49
print("Element at Array 2 Row 1, Column 3:", arr[1, 3, 4]) 

Element at Array 0 Row 0, Column 0: 10
Element at Array 0  Row 2, Column 4: 24
Element at Arry 1 Row 0, Column 3: 37
Element at Arry 1 Row 2, Column 3: 43
Element at Arry 2 Row 0, Column 4: 54
Element at Arry 2 Row 3, Column 1: 66
Element at Arry 2 Row 1, Column 3: 58
Element at Arry 2 Row 1, Column 3: 49


In [9]:
# Section B – Access Complete Rows

# Write a statement to extract:

#1. [15, 16, 17, 18, 19]
    print("All the row 1 elements of Array 0 :", arr[0, 1, :]) 

#2. [40, 41, 42, 43, 44]
print("All the row 2 elements of Array 1 :", arr[1, 2, :]) 

#3. [65, 66, 67, 68, 69]
print("All the row 3 elements of Array 2 :", arr[2, 3, :]) 

All the row elements of Array 0 : [15 16 17 18 19]
All the row elements of Array 1 : [40 41 42 43 44]
All the row elements of Array 1 : [65 66 67 68 69]


In [17]:
# Section C – Access Complete 2D Matrices

# Extract:

#The first matrix
print("First Matrix :\n", arr[0]) 
#The second matrix
print("Second Matrix :\n", arr[1]) 
#The third matrix
print("Third Matrix :\n", arr[2]) 

First Matrix :
 [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
Second Matrix :
 [[30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
Third Matrix :
 [[50 51 52 53 54]
 [55 56 57 58 59]
 [60 61 62 63 64]
 [65 66 67 68 69]]


In [23]:
# Section D – Column Extraction
#1 [10, 15, 20, 25]
print("Column Extraction [10, 15, 20, 25] :\n", arr[0,:,0]) 

#2 [32, 37, 42, 47]
print("Column Extraction [32, 37, 42, 47] :\n", arr[1,:,2]) 

#3 [54, 59, 64, 69]
print("Column Extraction [54, 59, 64, 69] :\n", arr[2,:,4]) 

Column Extraction [10, 15, 20, 25] :
 [10 15 20 25]
Column Extraction [32, 37, 42, 47] :
 [32 37 42 47]
Column Extraction [54, 59, 64, 69] :
 [54 59 64 69]


In [33]:
# Section E – Slicing

#Extract:

#The first two matrices.
print("First Two matrices \n" ,arr[0:2, :, :])
#The last two matrices.
print("Last Two matrices \n" ,arr[1:3, :, :])
#The first two rows from every matrix.
print("First two rows from every matrix \n" ,arr[:, 0:2, :])
#The last two rows from every matrix.
print("last two rows from every matrix. \n" ,arr[:, 2:4, :])
#The first three columns from every matrix.
print("first three columns from every matrix. \n" ,arr[:, :, 0:4])
#The last two columns from every matrix.
print("last two columns from every matrix. \n" ,arr[:, :, 3:5])

First Two matrices 
 [[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]
Last Two matrices 
 [[[30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
First two rows from every matrix 
 [[[10 11 12 13 14]
  [15 16 17 18 19]]

 [[30 31 32 33 34]
  [35 36 37 38 39]]

 [[50 51 52 53 54]
  [55 56 57 58 59]]]
last two rows from every matrix. 
 [[[20 21 22 23 24]
  [25 26 27 28 29]]

 [[40 41 42 43 44]
  [45 46 47 48 49]]

 [[60 61 62 63 64]
  [65 66 67 68 69]]]
first three columns from every matrix. 
 [[[10 11 12 13]
  [15 16 17 18]
  [20 21 22 23]
  [25 26 27 28]]

 [[30 31 32 33]
  [35 36 37 38]
  [40 41 42 43]
  [45 46 47 48]]

 [[50 51 52 53]
  [55 56 57 58]
  [60 61 62 63]
  [65 66 67 68]]]
last two columns from every matrix. 
 [[[13 14]
  [18 19]
  [23 24]
  [28 29]]

 [[33 34]
  [38 39

In [40]:
# Section F – Advanced Slicing

#[
# [10, 11, 12],
# [15, 16, 17]
#]
print("Advanced Slicing. \n" ,arr[0, 0:2, 0:3])

#[
# [42, 43, 44],
# [47, 48, 49]
#]
print("Advanced Slicing. \n" ,arr[1, 2:5, 2:5])

#[
# [55, 56],
# [60, 61],
# [65, 66]
#]
print("Advanced Slicing. \n" ,arr[2, 1:4, 0:2])

#[
# [13, 14],
# [18, 19]
#]
print("Advanced Slicing. \n" ,arr[0, 0:2, 3:5])

Advanced Slicing. 
 [[10 11 12]
 [15 16 17]]
Advanced Slicing. 
 [[42 43 44]
 [47 48 49]]
Advanced Slicing. 
 [[55 56]
 [60 61]
 [65 66]]
Advanced Slicing. 
 [[13 14]
 [18 19]]


In [56]:
# Section G –  Questions

#Write a single slicing statement to extract:

#Every alternate matrix.
print("Every alternate matrix. \n" ,arr[::2, :, :])

#Every alternate row from all matrices.
print("Every alternate row from all matrices. \n" ,arr[:, ::2, :])

#Every alternate column from all matrices.
print("Every alternate column from all matrices. \n" ,arr[:, ::, ::2])

#The first column from every matrix.
print("The first column from every matrix. \n" ,arr[:, :, 1])

#The last column from every matrix.
print("The last column from every matrix. \n" ,arr[:, :, 4])

#The middle row from every matrix.
print("The middle row from every matrix. \n" ,arr[:, 1:3, :])

#The middle column from every matrix.
print("The middle row from every matrix. \n" ,arr[:, :, 2])

#Reverse the order of matrices.
print("Reverse the order of matrices. \n" ,arr[:, ::-1, ::-1])
#Reverse the rows inside every matrix.
print("Reverse the order of matrices. \n" ,arr[:, ::-1, :])




Every alternate matrix. 
 [[[10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]

 [[50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
Every alternate row from all matrices. 
 [[[10 11 12 13 14]
  [20 21 22 23 24]]

 [[30 31 32 33 34]
  [40 41 42 43 44]]

 [[50 51 52 53 54]
  [60 61 62 63 64]]]
Every alternate column from all matrices. 
 [[[10 12 14]
  [15 17 19]
  [20 22 24]
  [25 27 29]]

 [[30 32 34]
  [35 37 39]
  [40 42 44]
  [45 47 49]]

 [[50 52 54]
  [55 57 59]
  [60 62 64]
  [65 67 69]]]
The first column from every matrix. 
 [[11 16 21 26]
 [31 36 41 46]
 [51 56 61 66]]
The last column from every matrix. 
 [[14 19 24 29]
 [34 39 44 49]
 [54 59 64 69]]
The middle row from every matrix. 
 [[[15 16 17 18 19]
  [20 21 22 23 24]]

 [[35 36 37 38 39]
  [40 41 42 43 44]]

 [[55 56 57 58 59]
  [60 61 62 63 64]]]
The middle row from every matrix. 
 [[12 17 22 27]
 [32 37 42 47]
 [52 57 62 67]]
Reverse the order of matrices. 
 [[[29 28 27 2